CREATE TABLE TBL_USER (
    USER_ID        VARCHAR2(32)  NOT NULL,
    USER_NAME      VARCHAR2(64)  NOT NULL,
    DEPT_NAME      VARCHAR2(32)  NOT NULL,
    DESCRP         CLOB              NULL,
    PASSWD         VARCHAR2(128) NOT NULL,
    LOGIN_FAILED   NUMBER(1)     DEFAULT 0 NOT NULL,
    INS_TIME       DATE          NOT NULL,
    UPD_TIME       DATE          NOT NULL,
    STATUS         VARCHAR2(3)   NOT NULL,
    constraint PK_USER PRIMARY KEY (USER_ID)
);
CREATE INDEX NDX_USER ON TBL_USER(STATUS);
COMMENT ON TABLE TBL_USER IS '사용자';
COMMENT ON COLUMN TBL_USER.USER_ID IS '사용자 ID';
COMMENT ON COLUMN TBL_USER.USER_NAME IS '사용자 이름';
COMMENT ON COLUMN TBL_USER.DEPT_NAME IS '부서 이름';
COMMENT ON COLUMN TBL_USER.DESCRP IS '설명';
COMMENT ON COLUMN TBL_USER.PASSWD IS '비밀번호';
COMMENT ON COLUMN TBL_USER.LOGIN_FAILED IS '로그인 실패 횟수';
COMMENT ON COLUMN TBL_USER.INS_TIME IS '등록 시간';
COMMENT ON COLUMN TBL_USER.UPD_TIME IS '수정 시간';
COMMENT ON COLUMN TBL_USER.STATUS IS '상태 - 001:사용, 998:잠김(locked), 999:제거(비사용))';

CREATE TABLE TBL_GROUP (
    GRP_TYPE    VARCHAR2(3)     NOT NULL,
    GRP_ID      VARCHAR2(3)     NOT NULL,
    GRP_NAME    VARCHAR2(64)    NOT NULL,
    DESCRP      CLOB                NULL,
    INS_ID      VARCHAR2(32)    NOT NULL,
    INS_TIME    DATE            NOT NULL,
    UPD_ID      VARCHAR2(32)    NOT NULL,
    UPD_TIME    DATE            NOT NULL,
    STATUS      VARCHAR2(3)     NOT NULL,
    constraint PK_GROUP PRIMARY KEY (GRP_TYPE, GRP_ID)
);
COMMENT ON TABLE TBL_GROUP IS '데이터 그룹';
COMMENT ON COLUMN TBL_GROUP.GRP_TYPE IS '그룹 유형';
COMMENT ON COLUMN TBL_GROUP.GRP_ID IS '그룹 아이디';
COMMENT ON COLUMN TBL_GROUP.GRP_NAME IS '그룹 이름';
COMMENT ON COLUMN TBL_GROUP.DESCRP IS '설명';
COMMENT ON COLUMN TBL_GROUP.INS_ID IS '등록자 아이디';
COMMENT ON COLUMN TBL_GROUP.INS_TIME IS '등록 시간';
COMMENT ON COLUMN TBL_GROUP.UPD_ID IS '수정자 아이디';
COMMENT ON COLUMN TBL_GROUP.UPD_TIME IS '수정 시간';
COMMENT ON COLUMN TBL_GROUP.STATUS IS '상태 - 001:사용, 999:제거(비사용)';

INSERT INTO TBL_GROUP (GRP_TYPE, GRP_ID, GRP_NAME, DESCRP, INS_ID, INS_TIME, UPD_ID, UPD_TIME)
SELECT '000' GRP_TYPE, A.*, 'admin' INS_ID, SYSDATE INS_TIME, 'admin' UPD_ID, SYSDATE UPD_TIME
FROM (
	SELECT '000' GRP_ID, '그룹 유형' GRP_NAME, 'TBL_GROUP.GRP_TYPE' DESCRP FROM DUAL UNION
	SELECT '001' GRP_ID, '공통 코드' GRP_NAME, 'TBL_CMN_CODE.GRP_ID' DESCRP FROM DUAL
) A;

CREATE TABLE TBL_CMN_CODE (
    GRP_ID      VARCHAR2(3)     NOT NULL COMMENT '(코드) 그룹 아이디',
    CD_ID       VARCHAR2(32)    NOT NULL COMMENT '코드',
    CD_VAL      VARCHAR2(64)    NOT NULL COMMENT '코드값',
    DESCRP      CLOB                NULL COMMENT '코드 설명',
    UPD_ID      VARCHAR2(32)    NOT NULL COMMENT '수정자 아이디',
    UPD_TIME    DATE            NOT NULL COMMENT '수정 일시',
    STATUS      VARCHAR2(3)	    NOT NULL COMMENT '상태 - 001:사용, 999:제거(비사용)',
    constraint PK_CMN_CODE PRIMARY KEY (GRP_ID, CD_ID)
);
COMMENT ON TABLE TBL_CMN_CODE IS '공통 코드';
COMMENT ON COLUMN TBL_CMN_CODE.GRP_ID IS '(코드) 그룹 아이디';
COMMENT ON COLUMN TBL_CMN_CODE.CD_ID IS '코드';
COMMENT ON COLUMN TBL_CMN_CODE.CD_VAL IS '코드값';
COMMENT ON COLUMN TBL_CMN_CODE.DESCRP IS '코드 설명';
COMMENT ON COLUMN TBL_CMN_CODE.UPD_ID IS '수정자 아이디';
COMMENT ON COLUMN TBL_CMN_CODE.UPD_TIME IS '수정 일시';
COMMENT ON COLUMN TBL_CMN_CODE.STATUS IS  '상태 - 001:사용; 999:제거(비사용)';

CREATE TABLE TBL_PERMISSION (
    PMS_ID      VARCHAR2(32)    NOT NULL,
    PMS_NAME    VARCHAR2(32)    NOT NULL,
    DESCRP      CLOB                NULL,
    UPD_ID      VARCHAR2(32)    NOT NULL,
    UPD_TIME    DATE            NOT NULL,
    constraint PK_PERMISSION PRIMARY KEY (PMS_ID),
    constraint UNQ_PMS_NAME UNIQUE (PMS_NAME)
);
COMMENT ON TABLE TBL_PERMISSION IS '권한';
COMMENT ON COLUMN TBL_PERMISSION.PMS_ID IS '권한 아이디';
COMMENT ON COLUMN TBL_PERMISSION.PMS_NAME IS '권한 이름';
COMMENT ON COLUMN TBL_PERMISSION.DESCRP IS '설명';
COMMENT ON COLUMN TBL_PERMISSION.UPD_ID IS '수정자 아이디';
COMMENT ON COLUMN TBL_PERMISSION.UPD_TIME IS '수정 시간';

CREATE TABLE TBL_PMS_ACTION (
    PMS_ID   VARCHAR2(32) NOT NULL COMMENT '권한 아이디',
    ACT_PATH VARCHAR2(32) NOT NULL COMMENT '액션 경로',
    INS_ID   VARCHAR2(32) NOT NULL COMMENT '등록자 아이디',
    INS_TIME DATE    NOT NULL COMMENT '등록 일시',
    constraint PK_PMS_ACTION PRIMARY KEY (PMS_ID, ACT_PATH)
);
COMMENT ON TABLE TBL_PMS_ACTION IS '권한-액션 매핑';
COMMENT ON TABLE TBL_PMS_ACTION.PMS_ID IS '권한 아이디';
COMMENT ON TABLE TBL_PMS_ACTION.ACT_PATH IS '액션 경로';
COMMENT ON TABLE TBL_PMS_ACTION.INS_ID IS '등록자 아이디';
COMMENT ON TABLE TBL_PMS_ACTION.INS_TIME IS '등록 시간';

CREATE TABLE TBL_MENU (
    MENU_ID      VARCHAR2(5)      NOT NULL,
    MENU_NAME    VARCHAR2(32)         NULL,
    ACT_PATH     VARCHAR2(32)         NULL,
    IMG_CFG      VARCHAR2(128)        NULL,
    PRNT_ID      VARCHAR2(5)      NOT NULL,
    SRT_ORD      NUMBER(2)        NOT NULL,
    UPD_ID       VARCHAR2(32)     NOT NULL,
    UPD_TIME     DATE             NOT NULL,
    STATUS       VARCHAR2(3)      NOT NULL,
    constraint PK_MENU PRIMARY KEY (MENU_ID)
);
COMMENT ON TABLE TBL_MENU IS '메뉴';
COMMENT ON COLUMN TBL_MENU.MENU_ID IS '메뉴 아이디';
COMMENT ON COLUMN TBL_MENU.MENU_NAME IS '메뉴 이름';
COMMENT ON COLUMN TBL_MENU.ACT_PATH IS '액션 경로';
COMMENT ON COLUMN TBL_MENU.IMG_CFG IS '이미지 설정(경로, 스타일 등)';
COMMENT ON COLUMN TBL_MENU.PRNT_ID IS '상위 메뉴 아이디';
COMMENT ON COLUMN TBL_MENU.SRT_ORD IS '정렬 순서';
COMMENT ON COLUMN TBL_MENU.UPD_ID IS '수정자 아이디';
COMMENT ON COLUMN TBL_MENU.UPD_TIME IS '수정 시간';
COMMENT ON COLUMN TBL_MENU.STATUS IS '상태 - 001:사용, 999:제거(비사용)'